# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldcorCpp <- function(dx, dy, w) {
    .Call('GIMLET_ldcorCpp', PACKAGE = 'GIMLET', dx, dy, w)
}

distCpp <- function(X, p) {
    .Call('GIMLET_distCpp', PACKAGE = 'GIMLET', X, p)
}

gaukerCpp <- function(X, mu, lambda) {
    .Call('GIMLET_gaukerCpp', PACKAGE = 'GIMLET', X, mu, lambda)
}

neikerCpp <- function(X, mu, r) {
    .Call('GIMLET_neikerCpp', PACKAGE = 'GIMLET', X, mu, r)
}

gimletCpp <- function(X, Y, Z, r, delta, bootn, type) {
    .Call('GIMLET_gimletCpp', PACKAGE = 'GIMLET', X, Y, Z, r, delta, bootn, type)
}

ldcorAllCpp <- function(X, Y, Z, M, delta, bootn, type) {
    .Call('GIMLET_ldcorAllCpp', PACKAGE = 'GIMLET', X, Y, Z, M, delta, bootn, type)
}

