# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldcorCpp <- function(dx, dy, w) {
    .Call(`_GIMLET_ldcorCpp`, dx, dy, w)
}

distCpp <- function(X, p) {
    .Call(`_GIMLET_distCpp`, X, p)
}

gaukerCpp <- function(X, mu, lambda) {
    .Call(`_GIMLET_gaukerCpp`, X, mu, lambda)
}

neikerCpp <- function(X, mu, r) {
    .Call(`_GIMLET_neikerCpp`, X, mu, r)
}

gimletCpp <- function(X, Y, Z, r, delta, nperm) {
    .Call(`_GIMLET_gimletCpp`, X, Y, Z, r, delta, nperm)
}

gimletCpp2 <- function(X, Y, Z, nperm) {
    .Call(`_GIMLET_gimletCpp2`, X, Y, Z, nperm)
}

ldcorAllCpp <- function(X, Y, Z, M, delta, nperm) {
    .Call(`_GIMLET_ldcorAllCpp`, X, Y, Z, M, delta, nperm)
}

rcpp_hello_world <- function() {
    .Call(`_GIMLET_rcpp_hello_world`)
}

